import { AttackScenario, VerificationSession } from '../types';

export const SAMPLE_SCENARIOS: AttackScenario[] = [
  {
    id: 'attack-deepfake-face',
    title: 'Midjourney + FaceSwap Live Impersonation',
    type: 'deepfake_face',
    threatLevel: 'CRITICAL',
    description: 'Real-time neural face swap overlay generated over a stolen identity document during live webcam challenge.',
    attackTechnique: 'Diffusion spatial warping & DeepFaceLive temporal interpolation',
    presetSession: {
      id: 'SESS-2026-8841',
      timestamp: new Date().toISOString(),
      sector: 'banking',
      candidateName: 'Elena Rostova (Claimed)',
      overallConfidence: 24,
      status: 'REJECTED',
      scores: {
        documentScore: 88,
        faceLivenessScore: 28,
        deepfakeRiskScore: 92,
        voiceAuthenticityScore: 71,
        behavioralScore: 82,
      },
      documentData: {
        fullName: 'ELENA ROSTOVA',
        documentType: 'Passport (EU Republic)',
        documentNumber: 'EU994827104',
        dateOfBirth: '1992-04-14',
        expiryDate: '2030-11-20',
        issuingCountry: 'Estonia',
        mrzChecksumValid: true,
        fontConsistency: '98% Match',
        hologramRefractionDetected: true,
      },
      livenessData: {
        headTurnVerified: false,
        blinkCount: 0,
        microExpressionsDetected: ['Static Eye Aperture', 'Unnatural Pupil Dilation'],
        rPPGPulseBpm: null, // No blood flow pulse!
        skinTextureAuthenticity: 18,
        spatialArtifactScore: 94,
      },
      voiceData: {
        passphraseSpoken: 'Aegis authorization eight four two nine',
        audioDurationSec: 3.4,
        pitchVarianceHz: 12.4,
        syntheticAcousticGlitchDetected: false,
        phaseCoherenceScore: 76,
      },
      behavioralData: {
        mouseCurvatureEntropy: 0.82,
        keypressDynamicsMs: 142,
        cognitiveResponseDelaySec: 2.1,
        botPatternProbability: 12,
      },
      xaiAttributions: [
        {
          feature: 'Photoplethysmography (rPPG) Pulse',
          modality: 'liveness',
          impact: -88,
          description: 'Absence of periodic subcutaneous vascular blood flow color fluctuations on cheek and forehead region.',
          status: 'anomaly',
        },
        {
          feature: 'High-Frequency Spectral Noise',
          modality: 'deepfake',
          impact: -92,
          description: 'Fourier transform reveals grid-like generative latent artifacts around jawline boundary.',
          status: 'anomaly',
        },
        {
          feature: 'Pupil & Iris Light Reflection',
          modality: 'deepfake',
          impact: -74,
          description: 'Catchlight highlights in left vs right eye lack geometric optical symmetry.',
          status: 'suspicious',
        },
        {
          feature: 'Document Checksum & MRZ Line',
          modality: 'document',
          impact: 82,
          description: 'Machine Readable Zone check digit calculation passed with authentic OCR font spacing.',
          status: 'normal',
        },
      ],
      decisionNodes: [
        {
          id: 'N1',
          step: 'Document Validation',
          condition: 'MRZ Checksum & Document Structure',
          result: 'pass',
          confidence: 94,
          reasoning: 'Authentic passport format with valid checksum digits.',
        },
        {
          id: 'N2',
          step: 'Biometric Face Match',
          condition: 'Document Portrait vs Live Webcam Stream',
          result: 'pass',
          confidence: 86,
          reasoning: 'Coarse facial feature geometry aligns with ID card portrait.',
        },
        {
          id: 'N3',
          step: 'Face Liveness & Micro-Expression',
          condition: 'rPPG Blood Flow Pulse & Micro-blink Verification',
          result: 'fail',
          confidence: 99,
          reasoning: 'ZERO blood volume pulse detected on facial capillaries. Static blink frequency.',
        },
        {
          id: 'N4',
          step: 'Deepfake Spectral Neural Classifier',
          condition: 'Generative GAN / Diffusion Artifact Inspection',
          result: 'fail',
          confidence: 96,
          reasoning: 'Deepfake probability 92%. Spatial boundary warping along jawline.',
        },
      ],
      summaryReasoning: 'CRITICAL THREAT: High-probability synthetic face swap detected. While the presented passport is physically valid, the live webcam feed exhibits 92% deepfake probability with complete absence of subcutaneous blood flow (rPPG pulse) and high-frequency generative spatial artifacts around the facial perimeter.',
      complianceBadges: ['KYC Level 3 Failed', 'AML Red Flag', 'Biometric Fraud Intercepted'],
      riskFactors: ['Deepfake Facial Swap (92%)', 'rPPG Pulse Missing', 'Catchlight Symmetry Error', 'Head Rotation Tracking Mismatch'],
    },
  },
  {
    id: 'attack-voice-clone',
    title: 'ElevenLabs Voice Clone + Synthetic Audio Injection',
    type: 'voice_clone',
    threatLevel: 'HIGH',
    description: 'Neural voice clone trained on 15 seconds of target executive audio attempting remote high-value transaction authorization.',
    attackTechnique: 'Acoustic feature conversion with neural vocoder synthesis',
    presetSession: {
      id: 'SESS-2026-9012',
      timestamp: new Date().toISOString(),
      sector: 'banking',
      candidateName: 'Marcus Vance',
      overallConfidence: 38,
      status: 'FLAGGED',
      scores: {
        documentScore: 94,
        faceLivenessScore: 89,
        deepfakeRiskScore: 32,
        voiceAuthenticityScore: 19,
        behavioralScore: 78,
      },
      documentData: {
        fullName: 'MARCUS ARCHER VANCE',
        documentType: 'Driver License (California)',
        documentNumber: 'C8831092',
        dateOfBirth: '1985-09-22',
        expiryDate: '2028-09-22',
        issuingCountry: 'USA',
        mrzChecksumValid: true,
        fontConsistency: '100% Match',
        hologramRefractionDetected: true,
      },
      livenessData: {
        headTurnVerified: true,
        blinkCount: 3,
        microExpressionsDetected: ['Natural Zygomatic Muscle Movement'],
        rPPGPulseBpm: 72,
        skinTextureAuthenticity: 91,
        spatialArtifactScore: 12,
      },
      voiceData: {
        passphraseSpoken: 'Aegis authorization eight four two nine',
        audioDurationSec: 2.8,
        pitchVarianceHz: 1.2, // Unnaturally flat pitch curve!
        syntheticAcousticGlitchDetected: true,
        phaseCoherenceScore: 22,
      },
      behavioralData: {
        mouseCurvatureEntropy: 0.76,
        keypressDynamicsMs: 165,
        cognitiveResponseDelaySec: 1.8,
        botPatternProbability: 18,
      },
      xaiAttributions: [
        {
          feature: 'Pitch Contour Stability (F0 Fundamental Frequency)',
          modality: 'voice',
          impact: -85,
          description: 'Acoustic pitch variance is unnaturally static (1.2 Hz deviation vs 15-30 Hz natural human range).',
          status: 'anomaly',
        },
        {
          feature: 'Neural Vocoder Phase Discontinuity',
          modality: 'voice',
          impact: -78,
          description: 'Phase spectrum coherence shows high-frequency robotic frame splicing gaps above 8 kHz.',
          status: 'suspicious',
        },
        {
          feature: 'Real-time Facial Liveness',
          modality: 'liveness',
          impact: 89,
          description: 'Camera feed exhibits normal 72 BPM vascular pulse and genuine micro-expressions.',
          status: 'normal',
        },
      ],
      decisionNodes: [
        {
          id: 'N1',
          step: 'Facial Liveness & Document OCR',
          condition: 'Live Facial Stream & State ID',
          result: 'pass',
          confidence: 92,
          reasoning: 'Document is authentic and physical face liveness passed.',
        },
        {
          id: 'N2',
          step: 'Voice Biometric Synthesis Detection',
          condition: 'Spectral Formant & Pitch Contour Analysis',
          result: 'fail',
          confidence: 94,
          reasoning: 'Voice authenticity score 19%. Acoustic features match synthetic neural voice model profile.',
        },
      ],
      summaryReasoning: 'FLAGGED SECURITY RISK: High-fidelity voice clone detected during spoken passphrase challenge. While physical document and face liveness were verified, the voice sample exhibits 81% probability of AI voice synthesis due to unnaturally robotic pitch contour and vocoder phase discontinuities.',
      complianceBadges: ['Voice Biometrics Failed', 'High-Risk Review Queue'],
      riskFactors: ['Synthetic Voice Clone (81% Risk)', 'Flat F0 Pitch Deviation', 'High-Frequency Vocoder Glitches'],
    },
  },
  {
    id: 'attack-document-forge',
    title: 'AI GAN Forged Identity Card with Photoshop Layering',
    type: 'document_forge',
    threatLevel: 'HIGH',
    description: 'AI-generated identity card with manipulated portrait, synthetic MRZ text, and missing physical anti-counterfeiting micro-print.',
    attackTechnique: 'Generative ID Template Inpainting + Synthetic Text Generator',
    presetSession: {
      id: 'SESS-2026-9150',
      timestamp: new Date().toISOString(),
      sector: 'egov',
      candidateName: 'Viktor Krum (Fraudulent ID)',
      overallConfidence: 15,
      status: 'REJECTED',
      scores: {
        documentScore: 18,
        faceLivenessScore: 82,
        deepfakeRiskScore: 45,
        voiceAuthenticityScore: 86,
        behavioralScore: 89,
      },
      documentData: {
        fullName: 'VIKTOR KRUM',
        documentType: 'National ID Card',
        documentNumber: 'ID77200194A',
        dateOfBirth: '1998-01-05',
        expiryDate: '2027-01-05',
        issuingCountry: 'Bulgaria',
        mrzChecksumValid: false, // Checksum mismatch!
        fontConsistency: '42% Font Mismatch (Injected Arial)',
        hologramRefractionDetected: false,
      },
      livenessData: {
        headTurnVerified: true,
        blinkCount: 2,
        microExpressionsDetected: ['Natural Eyebrow Raise'],
        rPPGPulseBpm: 68,
        skinTextureAuthenticity: 88,
        spatialArtifactScore: 22,
      },
      voiceData: {
        passphraseSpoken: 'Aegis authorization eight four two nine',
        audioDurationSec: 3.1,
        pitchVarianceHz: 22.1,
        syntheticAcousticGlitchDetected: false,
        phaseCoherenceScore: 88,
      },
      behavioralData: {
        mouseCurvatureEntropy: 0.89,
        keypressDynamicsMs: 180,
        cognitiveResponseDelaySec: 1.5,
        botPatternProbability: 5,
      },
      xaiAttributions: [
        {
          feature: 'MRZ Checksum Algorithm',
          modality: 'document',
          impact: -95,
          description: '7-3-1 weight modulus checksum failed on document number field.',
          status: 'anomaly',
        },
        {
          feature: 'Micro-Print Font Kerning & DPI',
          modality: 'document',
          impact: -82,
          description: 'Injected font rendering detected on surname box with irregular pixel anti-aliasing.',
          status: 'anomaly',
        },
        {
          feature: 'Holographic Optical Variable Ink',
          modality: 'document',
          impact: -70,
          description: 'Diffractive optical element missing dynamic rainbow glare under simulated tilt lighting.',
          status: 'suspicious',
        },
      ],
      decisionNodes: [
        {
          id: 'N1',
          step: 'Document Structural OCR',
          condition: 'MRZ Validation & Font Texture Check',
          result: 'fail',
          confidence: 98,
          reasoning: 'Document authenticity score 18%. Invalid MRZ checksum and synthetic font insertion.',
        },
      ],
      summaryReasoning: 'REJECTED: Document forgery detected. The presented national ID card contains synthetic OCR text modifications, inconsistent font anti-aliasing, and an invalid MRZ check digit calculation.',
      complianceBadges: ['eIDAS Non-Compliant', 'Document Tampering Flagged'],
      riskFactors: ['MRZ Checksum Mismatch', 'Injected Font Layering', 'Missing Holographic Security Refraction'],
    },
  },
  {
    id: 'authentic-citizen',
    title: 'Legitimate Citizen Onboarding (Verified Applicant)',
    type: 'authentic_person',
    threatLevel: 'SAFE',
    description: 'Genuine passport holder undergoing live multimodal verification with authentic document, natural liveness, and organic voice response.',
    attackTechnique: 'N/A (Legitimate User)',
    presetSession: {
      id: 'SESS-2026-9901',
      timestamp: new Date().toISOString(),
      sector: 'banking',
      candidateName: 'Sophia Lin',
      overallConfidence: 98,
      status: 'VERIFIED',
      scores: {
        documentScore: 99,
        faceLivenessScore: 97,
        deepfakeRiskScore: 3, // Very low deepfake risk
        voiceAuthenticityScore: 96,
        behavioralScore: 95,
      },
      documentData: {
        fullName: 'SOPHIA MEI LIN',
        documentType: 'Passport (United States)',
        documentNumber: 'P558190342',
        dateOfBirth: '1995-12-08',
        expiryDate: '2032-05-18',
        issuingCountry: 'USA',
        mrzChecksumValid: true,
        fontConsistency: '100% Match',
        hologramRefractionDetected: true,
      },
      livenessData: {
        headTurnVerified: true,
        blinkCount: 4,
        microExpressionsDetected: ['Slight Smile', 'Eyebrow Movement', 'Natural Saccades'],
        rPPGPulseBpm: 74,
        skinTextureAuthenticity: 98,
        spatialArtifactScore: 2,
      },
      voiceData: {
        passphraseSpoken: 'Aegis authorization eight four two nine',
        audioDurationSec: 3.0,
        pitchVarianceHz: 28.4,
        syntheticAcousticGlitchDetected: false,
        phaseCoherenceScore: 96,
      },
      behavioralData: {
        mouseCurvatureEntropy: 0.94,
        keypressDynamicsMs: 195,
        cognitiveResponseDelaySec: 1.2,
        botPatternProbability: 1,
      },
      xaiAttributions: [
        {
          feature: 'Photoplethysmography (rPPG)',
          modality: 'liveness',
          impact: 98,
          description: 'Strong, regular 74 BPM blood volume pulse detected across facial micro-capillaries.',
          status: 'normal',
        },
        {
          feature: 'Spatial Frequency Spectrum',
          modality: 'deepfake',
          impact: 96,
          description: 'Zero generative AI lattice or diffusion artifacts detected; natural pore skin texture confirmed.',
          status: 'normal',
        },
        {
          feature: 'Voice Harmonic Acoustic Pattern',
          modality: 'voice',
          impact: 95,
          description: 'Natural glottal pulse, rich vocal formants, and organic 28.4 Hz pitch variation.',
          status: 'normal',
        },
        {
          feature: 'Security Hologram Refraction',
          modality: 'document',
          impact: 99,
          description: 'Authentic US passport state eagle hologram shimmer confirmed.',
          status: 'normal',
        },
      ],
      decisionNodes: [
        {
          id: 'N1',
          step: 'Document Authenticity Verification',
          condition: 'MRZ Checksum & Optical Feature Analysis',
          result: 'pass',
          confidence: 99,
          reasoning: '100% valid US Passport format with active hologram glare.',
        },
        {
          id: 'N2',
          step: 'Facial Biometric & Liveness Check',
          condition: 'rPPG Blood Flow & Micro-Expression Dynamics',
          result: 'pass',
          confidence: 97,
          reasoning: 'Genuine 74 BPM pulse, natural blinking, and authentic skin depth.',
        },
        {
          id: 'N3',
          step: 'Deepfake & Voice Clone Scanning',
          condition: 'Spectral GAN & Voice Phase Analysis',
          result: 'pass',
          confidence: 97,
          reasoning: 'Deepfake risk score 3%. Voice sample is organic human speech.',
        },
      ],
      summaryReasoning: 'SUCCESSFULLY VERIFIED: All multimodal verification checks passed with high confidence (98%). Document MRZ checksum, physical hologram glare, facial liveness pulse (rPPG), deepfake spectrum, and voice harmonics are fully authentic.',
      complianceBadges: ['KYC Level 3 Passed', 'AML Clean', 'eIDAS Verified', 'HIPAA Ready'],
      riskFactors: [],
    },
  },
];
